version: '3.9'

services:
  # app:
  #   build: .
  #   container_name: block_platform_app
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - .env
    # volumes:
    #   - .:/application/

  block_platform_db:
    image: postgres:16-alpine3.19
    container_name: block_platform_db_container
    volumes:
      - block_platform_db_v:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_USER: ${BLOCK_PLATFORM_USER}
      POSTGRES_PASSWORD: ${BLOCK_PLATFORM_PASSWORD}
      POSTGRES_DB: ${BLOCK_PLATFORM_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${BLOCK_PLATFORM_USER} -d ${BLOCK_PLATFORM_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  block_platform_db_v: